[project]
name = "video-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles==23.2.1",
    "fastapi==0.104.1",
    "gtts==2.5.1",
    "moviepy==1.0.3",
    "numpy>=2.5.0",
    "pydub==0.25.1",
    "python-multipart==0.0.6",
    "unsloth>=2026.6.9",
    "uvicorn==0.24.0",
    "torch==2.11.0+cu130",
    "torchaudio==2.11.0+cu130",
    "torchvision==0.26.0+cu130",
    "torchcodec==0.14.0+cu130",
    "soundfile>=0.14.0",
    "omegaconf>=2.3.1",
    "einx>=0.4.3",
    "einops>=0.8.2",
    "soxr>=1.1.0",
    "transformers>=4.56.2",
    "xformers>=0.0.35",
    "yt-dlp>=2026.7.4",
    "ctranslate2>=4.8.1",
    "faster-whisper>=1.2.1",
    "pyannote-audio>=4.0.7",
]
[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
torchcodec = { index = "pytorch-cu130" }

[tool.uv]
link-mode = "copy"
override-dependencies = [
    "torch==2.11.0+cu130",
    "torchaudio==2.11.0+cu130",
    "torchvision==0.26.0+cu130",
    "torchcodec==0.14.0+cu130",
]
